### PR TITLE
the thing is underlined red but I think it works correclty the compil…

### PR DESCRIPTION
**Pull request by AustinJia-code**
…er is funy sometimes

the thing is underlined red but I think it works correclty the compiler is funy sometimes,

Before issuing a pull request, please see the contributing page.

Before issuing a pull request, please see the contributing page.

Before issuing a pull request, please see the contributing page.

### CODE REVIEW

**Comment by AustinJia-code** [comment]
hmm no nvm on second thought I think the grammar is not the written right

**Comment by toptobes** [comment]
@AustinJia-code You misspelled "foo". Please correct asap.

**Comment by AustinJia-code** [comment]
I don't think we learned that at acc just delete it if you don't like how I do things...

**Comment by Seb-Robochoa** [comment]
see you soon :D

**Comment by toptobes** [comment]
Fine... LGETM

**Pull request merged**
